name: Simulation Test

on:
  # Triggers the workflow on pull request events but only for the 'main' branch
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  simulation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Download Modules
        run: go mod download

      - name: Test
        id: test
        run: go test -v -run=TestFullAppSimulation ./app -NumBlocks 200 -BlockSize 50 -Commit -Enabled -Period 1